### ISSUE TITLE
3.28.6更新時の確認事項

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/QGIS_maintenance#1]
@ageno-geo
3.28.6更新時の下記を確認の後に配信を実行してください！

 「LTR版の最新バージョンである標記のバージョンをインストールしたところ、クエリビルダ等の式入力部分で日本語(というよりIME経由での全角文字)の入力ができなくなりました。
確定しても、そのまま消えてしまうようです。

フィルタの入力等で支障をきたしていて、どうにもならなかったので、現在は一つ古い3.28.5に戻して使用しています。
こちらでは何も問題ありません。」

**Comment by yamamoto-ryuzo** [comment]
揚野さんへ　送信テストです。
必ず，このスレッドで返信ください。

**Comment by ageno-geo** [comment]
6月定期更新でのQGIS(3.28.6)バージョンアップは見送りました
文字入力の問題が解決するか、次のバージョンで問題ないことが確認できれば
次回にバージョンアップを行うようにします

**Comment by yamamoto-ryuzo** [comment]
了解しました。
