### ISSUE TITLE
スポット保守日程調整

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/QGIS_maintenance#4]
@ageno-geo 
次回スポット保守可能日を教えて回答ください。

**Comment by yamamoto-ryuzo** [comment]
@ageno-geo
次回スポット保守可能日を回答ください。

**Comment by ageno-geo** [comment]
@yamamoto-ryuzo 
7月6日(木)10:00~伺わせていただきます

**Comment by ageno-geo** [comment]
@yamamoto-ryuzo
先日は申し訳ございませんでした。
7月13日(木)10:00~伺わせていただきます

**Comment by city-soja-chiiki** [comment]
@ageno-geo
次回8月分の保守について，18日，30日が空いておりますが，ご都合の程いかがでしょうか。

**Comment by ageno-geo** [comment]
遅くなり申し訳ございません
8月18日金曜日でお願いします
前回同様11時位に伺わせていただきます

**Comment by city-soja-chiiki** [comment]
かしこまりました。よろしくお願いいたします。

**Comment by ageno-geo** [comment]
@city-soja-chiiki 申し訳ありません、風邪のため30日に延期させていただけますでしょうか

**Comment by city-soja-chiiki** [comment]
> @city-soja-chiiki 申し訳ありません、風邪のため30日に延期させていただけますでしょうか

かしこまりました。
再度日程調整させていただきます。

**Comment by city-soja-chiiki** [comment]
@ageno-geo
次回10月分の保守について，30日が空いておりますが，ご都合の程いかがでしょうか。
また，今月はタイミングが合わず日程の都合がつかなかったため、11月，12月で保守日数の調整をさせていただきます。

**Comment by ageno-geo** [comment]
@city-soja-chiiki 
調整ありがとうございます
では30日10時～伺わせていただきます
また、保守日数の調整についても承知しました

**Comment by yamamoto-ryuzo** [comment]
いったん、私の退職に伴いクローズします。
定期保守の話と混じっているようですが、その都度スレッドを立ち上げてください。
話が分からなくなる恐れがあります。
